name: big_wallet
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2

  email_validator: ^2.0.1

  flutter:
    sdk: flutter

  flutter_native_splash: ^1.2.0

  flutter_screenutil: ^5.0.0-nullsafety.11

  flutter_svg: ^0.22.0

  get: ^4.1.4

  google_fonts: ^2.0.0

  http: ^0.13.3

  image_cropper: ^1.4.1

  image_picker: ^0.8.0+3

  internet_connection_checker: ^0.0.1+1

  logger: ^1.0.0

  permission_handler: ^8.0.0+1

  pinput: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
